
TARGETS = list0401 list0402 list0403 list0404 list0405


all : $(TARGETS)

list0401 : list0401.c
	gcc -Wall -ggdb list0401.c -o list0401

list0402 : list0402.c
	gcc -Wall -ggdb list0402.c -o list0402

list0403 : list0403.c
	gcc -Wall -ggdb list0403.c -o list0403

list0404 : list0404.c
	gcc -Wall -ggdb list0404.c -o list0404

list0405 : list0405.c
	gcc -Wall -ggdb list0405.c -o list0405


	
clean :
	rm -f $(TARGETS) core
