TARGETS = list0601 list0602 list0603


all : $(TARGETS)

list0601 : list0601.c
	gcc -Wall -ggdb list0601.c -o list0601

list0602 : list0602.c
	gcc -Wall -ggdb list0602.c -o list0602

list0603 : list0603.c
	gcc -Wall -ggdb list0603.c -o list0603



	
clean :
	rm -f $(TARGETS) core
