TARGETS = list1801 list1802 list1803 list1804 list1805 list1806


all : $(TARGETS)

list1801 : list1801.c
	gcc -Wall -ggdb list1801.c -o list1801

list1802 : list1802.c
	gcc -Wall -ggdb list1802.c -o list1802

list1803 : list1803.c
	gcc -Wall -ggdb list1803.c -o list1803

list1804 : list1804.c
	gcc -Wall -ggdb list1804.c -o list1804

list1805 : list1805.c
	gcc -Wall -ggdb list1805.c -o list1805

list1806 : list1806.c
	gcc -Wall -ggdb list1806.c -o list1806


	
clean :
	rm -f $(TARGETS) core
