TARGETS = list0901 list0902 list0903 list0904 list0905


all : $(TARGETS)

list0901 : list0901.c
	gcc -Wall -ggdb list0901.c -o list0901

list0902 : list0902.c
	gcc -Wall -ggdb list0902.c -o list0902

list0903 : list0903.c
	gcc -Wall -ggdb list0903.c -o list0903

list0904 : list0904.c
	gcc -Wall -ggdb list0904.c -o list0904

list0905 : list0905.c
	gcc -Wall -ggdb list0905.c -o list0905



	
clean :
	rm -f $(TARGETS) core
