#!/usr/bin/env python3
#
# Copyright (c) 2019 SUSE Linux AG, Nuernberg, Germany.
# All rights reserved.
#
# Authors:  Gernot Payer <gpayer@suse.de>
#			Craig Salmond <csalmond@suse.com> 2006-2019
#
# A wrapper script to run a given test as a child process and
# to control this process.
#
# return codes:
#	0: success
#	1: failure
#	2: pass with warning
#	3: not applicable
#	4: not supported. Used to be: failure (for tests that run to termination no matter what) - returns a 1 to test console
#	5: not testable. Used to be: not supported (returns 4 to TestConsole)
#

import os,glob
import sys,time
import signal
import re
import string
import subprocess
#import commands
XsessionFile = '~/myprog/python/online-tutorials/xsession'
subprocess.call(['/bin/bash','export','>',XsessionFile])

try:
	os.stat( "/etc/SuSE-release" )
	with open( "/etc/SuSE-release" ) as f:
		for line in f:
			if re.search("VERSION =", line) != None:
#				ver = string.split( line, " " ) python2.x
				ver = "".split( line, " " ) #New python 3.x
				print("ver list: " + ver)
				osVer = ver[2]
				print(osVer)
			if re.search("PATCHLEVEL =", line) != None:
#				sp = string.split( line ) python 2.x
				sp = "".split( line ) #New python 3.x
				osVer = ver[2] + "." + sp[2]
except FileNotFoundError as e:
	#print(e)
	with open( "/etc/os-release" ) as f:
		for line in f:
			if re.search("VERSION=", line) != None:
				ver = line.split('"' )				
				osVer = ver[1]
				print(osVer)
finally:
		f.close()		