TARGETS = list1001 list1002 list1003 list1004 list1005 list1006 list1007


all : $(TARGETS)

list1001 : list1001.c
	gcc -Wall -ggdb list1001.c -o list1001

list1002 : list1002.c
	gcc -Wall -ggdb list1002.c -o list1002

list1003 : list1003.c
	gcc -Wall -ggdb list1003.c -o list1003

list1004 : list1004.c
	gcc -Wall -ggdb list1004.c -o list1004

list1005 : list1005.c
	gcc -Wall -ggdb list1005.c -o list1005

list1006 : list1006.c
	gcc -Wall -ggdb list1006.c -o list1006

list1007 : list1007.c
	gcc -Wall -ggdb list1007.c -o list1007


	
clean :
	rm -f $(TARGETS) core
