TARGETS = list1701 list1702 list1703 list1704 list1705 list1706 list1706


all : $(TARGETS)

list1701 : list1701.c
	gcc -Wall -ggdb list1701.c -lm -o list1701

list1702 : list1702.c
	gcc -Wall -ggdb list1702.c -o list1702

list1703 : list1703.c
	gcc -Wall -ggdb list1703.c -o list1703

list1704 : list1704.c
	gcc -Wall -ggdb list1704.c -o list1704

list1705 : list1705.c
	gcc -Wall -ggdb list1705.c -o list1705

list1706 : list1706.c
	gcc -Wall -ggdb list1706.c -o list1706

list1707 : list1707.c
	gcc -Wall -ggdb list1707.c -o list1707


	
clean :
	rm -f $(TARGETS) core
