TARGETS = list1901 list1902 list1903 list1904 list1905 list1906 list1907 list1908


all : $(TARGETS)

list1901 : list1901.c
	gcc -Wall -ggdb list1901.c -o list1901

list1902 : list1902.c
	gcc -Wall -ggdb list1902.c -o list1902

list1903 : list1903.c
	gcc -Wall -ggdb list1903.c -o list1903

list1904 : list1904.c
	gcc -Wall -ggdb list1904.c -o list1904

list1905 : list1905.c
	gcc -Wall -ggdb list1905.c -o list1905

list1906 : list1906.c
	gcc -Wall -ggdb list1906.c -o list1906

list1907 : list1907.c
	gcc -Wall -ggdb list1907.c -o list1907

list1908 : list1908.c
	gcc -Wall -ggdb list1908.c -o list1908


	
clean :
	rm -f $(TARGETS) core
