TARGETS = list0501 list0502 list0503 list0504 list0505


all : $(TARGETS)

list0501 : list0501.c
	gcc -Wall -ggdb list0501.c -o list0501

list0502 : list0502.c
	gcc -Wall -ggdb list0502.c -o list0502

list0503 : list0503.c
	gcc -Wall -ggdb list0503.c -o list0503

list0504 : list0504.c
	gcc -Wall -ggdb list0504.c -o list0504

list0505 : list0505.c
	gcc -Wall -ggdb list0505.c -o list0505


	
clean :
	rm -f $(TARGETS) core
