TARGETS = list0801 list0802 list0803 list0804 list0805 list0806 list0807


all : $(TARGETS)

list0801 : list0801.c
	gcc -Wall -ggdb list0801.c -o list0801

list0802 : list0802.c
	gcc -Wall -ggdb list0802.c -o list0802

list0803 : list0803.c
	gcc -Wall -ggdb list0803.c -o list0803

list0804 : list0804.c
	gcc -Wall -ggdb list0804.c -o list0804

list0805 : list0805.c
	gcc -Wall -ggdb list0805.c -o list0805

list0806 : list0806.c
	gcc -Wall -ggdb list0806.c -o list0806

list0807 : list0807.c
	gcc -Wall -ggdb list0807.c -o list0807



	
clean :
	rm -f $(TARGETS) core
