TARGETS = list1601 list1602 list1603 list1604 list1605 list1606 list1607 list1608 \
          list1609 list1610 list1611 list1612 list1613 list1614 list1615


all : $(TARGETS)

list1601 : list1601.c
	gcc -Wall -ggdb list1601.c -o list1601

list1602 : list1602.c
	@echo "*****************************************"
	@echo "* This will generate a warning message. *"
	@echo "*****************************************"
	gcc -Wall -ggdb list1602.c -o list1602

list1603 : list1603.c
	gcc -Wall -ggdb list1603.c -o list1603

list1604 : list1604.c
	gcc -Wall -ggdb list1604.c -o list1604

list1605 : list1605.c
	gcc -Wall -ggdb list1605.c -o list1605

list1606 : list1606.c
	gcc -Wall -ggdb list1606.c -o list1606

list1607 : list1607.c
	gcc -Wall -ggdb list1607.c -o list1607

list1608 : list1608.c
	gcc -Wall -ggdb list1608.c -o list1608

list1609 : list1609.c
	gcc -Wall -ggdb list1609.c -o list1609

list1610 : list1610.c
	gcc -Wall -ggdb list1610.c -o list1610

list1611 : list1611.c
	gcc -Wall -ggdb list1611.c -o list1611

list1612 : list1612.c
	gcc -Wall -ggdb list1612.c -o list1612

list1613 : list1613.c
	gcc -Wall -ggdb list1613.c -o list1613

list1614 : list1614.c
	gcc -Wall -ggdb list1614.c -o list1614

list1615 : list1615.c
	gcc -Wall -ggdb list1615.c -o list1615


	
clean :
	rm -f $(TARGETS) core
